# Generated by Django 2.2 on 2019-04-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_auto_20190418_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='coupon_id',
            field=models.CharField(default='co', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
