# Generated by Django 2.2 on 2019-04-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0003_offer_coupon_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='code',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='coupon_id',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='offer_value',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='product',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='verified_on',
        ),
    ]
