# Generated by Django 2.2 on 2019-04-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0004_auto_20190419_1427'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
